# Generated by Django 4.0.4 on 2022-05-21 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msgmodel',
            old_name='massage',
            new_name='message',
        ),
    ]
