# Generated by Django 4.0.4 on 2022-05-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app3', '0002_rename_massage_msgmodel_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='msgModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
