# Generated by Django 4.0.4 on 2022-05-21 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app3', '0004_msgmodel2_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='msgModel2',
        ),
    ]
