# Generated by Django 4.0.4 on 2022-05-22 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app3', '0005_delete_msgmodel2'),
    ]

    operations = [
        migrations.CreateModel(
            name='msgModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by',
                                                 to='app3.msgmodel')),
            ],
        ),
    ]
