# Generated by Django 4.0.4 on 2022-05-22 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app3', '0008_remove_msgmodel2_created_by_msgmodel_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgmodel',
            name='created_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
