# Generated by Django 4.0.4 on 2022-05-22 12:25

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app3', '0009_alter_msgmodel_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msgmodel2',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='msgmodel2',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='msgmodel2',
            name='email',
        ),
        migrations.RemoveField(
            model_name='msgmodel2',
            name='id',
        ),
        migrations.RemoveField(
            model_name='msgmodel2',
            name='username',
        ),
        migrations.AddField(
            model_name='msgmodel2',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE,
                                       parent_link=True, primary_key=True, serialize=False,
                                       to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='msgmodel',
            name='created_by',
            field=models.ManyToManyField(to='app3.msgmodel2'),
        ),
    ]
