# Generated by Django 4.0.4 on 2022-05-22 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app3', '0011_alter_msgmodel_created_by_delete_msgmodel2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='msgModel2',
        ),
    ]
