# Generated by Django 4.0.4 on 2022-05-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app3', '0012_delete_msgmodel2'),
    ]

    operations = [
        migrations.CreateModel(
            name='messagemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='msgmodel',
            name='created_by',
            field=models.ManyToManyField(to='app3.messagemodel'),
        ),
    ]
